// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudAyuda.Model;

namespace SolicitudAyuda.Model.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210205135052_boon2")]
    partial class boon2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Maestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeroApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeccionalId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeccionalId");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.RequisitoTipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PossibleValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("PossibleValues");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("RequisitosTiposSolicitud");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Comunicacion solicitud del interesado dirigida al CEN",
                            FormName = "rdcomunicacion",
                            PossibleValues = "",
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Copia de cedula",
                            FormName = "rdcopiacedula",
                            PossibleValues = "",
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Expediente clinico que demuestre diagnostico actualizado",
                            FormName = "rdexpendiente",
                            PossibleValues = "",
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Carta aval de la seccional a la que pertenece",
                            FormName = "rdcartaaval",
                            PossibleValues = "",
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "ARS a que pertenece",
                            FormName = "rdars",
                            PossibleValues = "ARS CMD,ARS APS,ARS SIMAG,ARS GRUPO MEDICO ASOCIADO,ARS YUNEN,ARS UNIVERSAL,ARS MONUMENTAL,ARS FUTURO,ARS PRIMERA,ARS ASEMAP,ARS SEMMA,ARS RENACER,ARS PALIC-SALUD,ARS PLAN SALUD,ARS SENASA,ARS RESERVAS,ARS METASALUD,ARS SENASA - REGIMEN SUBSIDIADO",
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Comunicacion solicitud del interesado dirigida al CEN",
                            FormName = "rdcomunicacion",
                            PossibleValues = "",
                            TipoSolicitudId = 2
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Copia de cedula",
                            FormName = "rdcopiacedula",
                            PossibleValues = "",
                            TipoSolicitudId = 2
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Carta aval de la seccional a la que pertenece",
                            FormName = "rdcartaaval",
                            PossibleValues = "",
                            TipoSolicitudId = 2
                        });
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Seccional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PresidenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Seccionales");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TiposSolictudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Construccion"
                        });
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Maestro", b =>
                {
                    b.HasOne("SolicitudAyuda.Model.Entities.Seccional", "Seccional")
                        .WithMany("Maestros")
                        .HasForeignKey("SeccionalId");

                    b.Navigation("Seccional");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Municipio", b =>
                {
                    b.HasOne("SolicitudAyuda.Model.Entities.Provincia", "Provincia")
                        .WithMany("Municipios")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.RequisitoTipoSolicitud", b =>
                {
                    b.HasOne("SolicitudAyuda.Model.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Requisitos")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Seccional", b =>
                {
                    b.HasOne("SolicitudAyuda.Model.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Provincia", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.Seccional", b =>
                {
                    b.Navigation("Maestros");
                });

            modelBuilder.Entity("SolicitudAyuda.Model.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
